# Nombre del servicio
spring.application.name=ms-auth

# Puerto
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/db_auth
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=tienda-generica-secret-key-2024-muy-larga-para-seguridad
jwt.expiration=86400000