# Nombre del servicio
spring.application.name=ms-auth

# Puerto
server.port=8081


# PostgreSQL
# Conexión limpia y directa a la Base de Datos de Railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
ms.usuarios.url=http://ms-usuarios:8083
jwt.secret=tienda-generica-secret-key-2024-muy-larga-para-seguridad
jwt.expiration=86400000

logging.level.org.springframework.web=DEBUG